#!/usr/bin/env bash
name='mt-turkman'
release='1'
version='1.0'
url='https://turkman.gitlab.io/'
description='mt-turkman wallpapers, HamoniKR and Orchis Themes'
email='mobilturka@proton.me'
maintainer='mobilturka'
license=('GPLv3')
source=("./mt-turkman.zip")
depends=()
makedepends=()
sha256sums=('SKIP')
group=(x11.themes)
uses=()
arch=('x86_64')

package() {
  cd $name
  make SHELL="/bin/bash -x" DESTDIR="$DESTDIR" install
}
