#!/bin/bash
# Turkman Linux için Firefox Beta kurucu rootsuz bash thunderbird komutu ile çalıştırın!

wget -O /tmp/thunderbird.tar.bz2 "https://download.mozilla.org/?product=thunderbird-latest-ssl&os=linux64&lang=tr"
mkdir ~/.local/share/applications
cat >> /data/user/$USER/.local/share/applications/Thunderbird.desktop << EOF
[Desktop Entry]
Type=Application
Name=Thunderbird
Comment=Thunderbird
Exec=/data/user/$USER/.local/thunderbird/thunderbird
Icon=/data/user/$USER/.local/thunderbird/chrome/icons/default/default128.png
Categories=Network;
StartupNotify=false
Terminal=false
EOF
tar -xvf /tmp/thunderbird.tar.bz2 -C ~/.local