#!/bin/bash
# Turkman Linux için Firefox Beta kurucu rootsuz bash firefox-beta komutu ile çalıştırın!

wget -O /tmp/firefox-beta.tar.bz2 "https://download.mozilla.org/?product=firefox-beta-latest-ssl&os=linux64&lang=tr"

mkdir ~/.local/share/applications
cat >> ~/.local/share/applications/firefox-beta.desktop << EOF
[Desktop Entry]
Version=1.0
Name=Firefox Beta
Comment=İnternet'te Gezinin
GenericName=Web Tarayıcı
Keywords=Internet;WWW;Browser;Web;Explorer
Exec=/data/user/$USER/.local/firefox-beta/firefox
Terminal=false
X-MultipleArgs=false
Type=Application
Icon=/data/user/$USER/.local/firefox-beta/browser/chrome/icons/default/default128.png
Categories=GNOME;GTK;Network;WebBrowser;
MimeType=text/html;text/xml;application/xhtml+xml;application/xml;application/rss+xml;application/rdf+xml;image/gif;image/jpeg;image/png;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/ftp;x-scheme-handler/chrome;video/webm;application/x-xpinstall;
StartupNotify=true
EOF
tar -xvf /tmp/firefox-beta.tar.bz2 -C ~/.local/
mv ~/.local/firefox ~/.local/firefox-beta
